#### <span style="color: deepskyblue;">Analiza dotycząca oferowanych powierzchni nieruchomości w ujęciu geograficznym   </span>

In [17]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as ss
import seaborn as sns
import missingno as msno
import plotly.express as px

%matplotlib inline 
%config InlineBackend.figure_format = 'retina'

df = pd.read_csv("../data/apartments_clean.csv", sep=';', encoding="cp1250")
df.head(3)

C:\Users\Grażyna\AppData\Local\Temp\ipykernel_7888\2229932719.py:12: DtypeWarning: Columns (0: address) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/apartments_clean.csv", sep=';', encoding="cp1250")

,id,category,title,bathrooms,bedrooms,currency,fee,has_photo,pets_allowed,price,...,Playground,Pool,Refrigerator,Storage,TV,Tennis,View,Washer Dryer,Wood Floors,price_per_sqft
0,5668640009,housing/rent/apartment,One BR 507 & 509 Esplanade,1.0,1.0,USD,No,Thumbnail,Cats,2195.0,...,0,0,0,0,0,0,0,0,0,4.049815
1,5668639818,housing/rent/apartment,Three BR 146 Lochview Drive,1.5,3.0,USD,No,Thumbnail,"Cats,Dogs",1250.0,...,0,0,0,0,0,0,0,0,0,0.833333
2,5668639686,housing/rent/apartment,Three BR 3101 Morningside Drive,2.0,3.0,USD,No,Thumbnail,NaN,1395.0,...,0,0,0,0,0,0,0,0,0,0.845455

Skróty stref czasowych użyte w tabeli df_state:
- EST (Wschodnia), 
- CST (Centralna), 
- MST (Górska), 
- PST (Pacyficzna), 
- AKST (Alaska), 
- HST (Hawaje). 

Plik grupujący stany USA wg różnych kategorii pozyskany jest z pomocą AI ze strony U.S. Census Bureau (Biuro Spisu Ludności USA).</BR> 
Oznaczenie „Tak” w kolumnach <span style="color: deepskyblue;">Stan rolniczy</span>, <span style="color: deepskyblue;">Stan przemysłowy</span>, <span style="color: deepskyblue;">Ważny turystycznie</span> wskazuje,</BR> że dany sektor stanowi kluczowy, wyróżniający się filar gospodarki lub tożsamości stanu na tle reszty kraju

In [18]:
df_state = pd.read_csv("../data/przypisanie_stanowUSA.csv", sep=';', encoding="cp1250")
df_state.head(3)

,Stan,Skrot,Region,Strefa czasowa,Stan rolniczy,Stan przemyslowy,Wazny turystycznie
0,Alabama,AL,South,CST / EST,Tak,Tak,Nie
1,Alaska,AK,West,AKST / PST,Nie,Nie,Tak
2,Arizona,AZ,West,MST,Nie,Tak,Tak

In [19]:

# dołącz nazwę stanu
df = df.merge(
    df_state[['Skrot', 'Stan']],
    left_on='state',
    right_on='Skrot',
    how='left'
)
# usuń pomocniczą kolumnę
df = df.drop(columns='Skrot')

# dołącz region
df = df.merge(
    df_state[['Skrot', 'Region']],
    left_on='state',
    right_on='Skrot',
    how='left'
)
# usuń pomocniczą kolumnę
df = df.drop(columns='Skrot')

# dołącz Strefa czasowa
df = df.merge(
    df_state[['Skrot', 'Strefa czasowa']],
    left_on='state',
    right_on='Skrot',
    how='left'
)
# usuń pomocniczą kolumnę
df = df.drop(columns='Skrot')

# dołącz Stan rolniczy
df = df.merge(
    df_state[['Skrot', 'Stan rolniczy']],
    left_on='state',
    right_on='Skrot',
    how='left'
)
# usuń pomocniczą kolumnę
df = df.drop(columns='Skrot')

# dołącz Stan przemyslowy
df = df.merge(
    df_state[['Skrot', 'Stan przemyslowy']],
    left_on='state',
    right_on='Skrot',
    how='left'
)
# usuń pomocniczą kolumnę
df = df.drop(columns='Skrot')

# dołącz Wazny turystycznie
df = df.merge(
    df_state[['Skrot', 'Wazny turystycznie']],
    left_on='state',
    right_on='Skrot',
    how='left'
)
# usuń pomocniczą kolumnę
df = df.drop(columns='Skrot')

df.head(3)

,id,category,title,bathrooms,bedrooms,currency,fee,has_photo,pets_allowed,price,...,View,Washer Dryer,Wood Floors,price_per_sqft,Stan,Region,Strefa czasowa,Stan rolniczy,Stan przemyslowy,Wazny turystycznie
0,5668640009,housing/rent/apartment,One BR 507 & 509 Esplanade,1.0,1.0,USD,No,Thumbnail,Cats,2195.0,...,0,0,0,4.049815,California,West,PST,Tak,Tak,Tak
1,5668639818,housing/rent/apartment,Three BR 146 Lochview Drive,1.5,3.0,USD,No,Thumbnail,"Cats,Dogs",1250.0,...,0,0,0,0.833333,Virginia,South,EST,Nie,Tak,Tak
2,5668639686,housing/rent/apartment,Three BR 3101 Morningside Drive,2.0,3.0,USD,No,Thumbnail,NaN,1395.0,...,0,0,0,0.845455,North Carolina,South,EST,Tak,Tak,Tak